### ISSUE TITLE
Eigen 3.4 release update

### ISSUE THREAD

**Issue by zdebruine** [RcppCore/RcppEigen#101]
Thanks all for maintaining this fundamental resource for the R community!

Seeing that Eigen 3.4 is out, and it supports some very useful operations for matrix subsetting and reshaping, what is the plan for when these updates will be loaded into RcppEigen?

Thanks again!

**Comment by eddelbuettel** [comment]
See #123 -- help with RcppEigen towards Eigen 3.4.0 would be greatly appreciated.

**Comment by eddelbuettel** [comment]
We're there now -- see #103 and PR #102 -- and it is arriving on CRAN now.
