### ISSUE TITLE
fine-grained access to features

### ISSUE THREAD

**Issue by waynelapierre** [RcppCore/RcppEigen#111]
Eigen is slow to compile. Have you considered providing new header files similar to Rcpp/Light, Rcpp/Lighter, Rcpp/Lightest to RcppEigen? Eigen already has a nice layout of Modules and Header files, which can be mapped to RcppEigen. 
  
https://eigen.tuxfamily.org/dox/group__QuickRefPage.html

**Comment by eddelbuettel** [comment]
In theory, this could be done. In practice, a) nobody seems to be working on it and b) #103 has higher priority but nobody is making time for that either.  

Slightly related: at least for repeated compilation, as in package building, `ccache` is useful.  See e.g. [this blog post](https://dirk.eddelbuettel.com/blog/2017/11/27/).
