### ISSUE TITLE
compilation error in lmsol::gesdd

### ISSUE THREAD

**Issue by user296** [RcppCore/RcppEigen#113]
When installing the latest RcppEigen_0.3.3.9.2 in R, I get an error in fastLm.cpp, function lmsol::gesdd
fastLm.cpp:147:54 error expected `)` before FCONE

Seeing same error at fastLm.cpp:151:59.

Fix available?

**Comment by eddelbuettel** [comment]
We need more details:

- OS
- version
- hardware
- compiler version
- installation from source or binary?
- what `sessionInfo()` says about BLAS/LAPACK
- whatever else matters 

The package is a decade+ old, and has been testing a bazillion times at CRAN alone.  Running `fastLm` is part of that.  If I had to guess, you are on a system with an incomplete BLAS.

Oh, now I know.  You are on ancient compiler.  R defines the FCONE macros for a minuscule technical matter related to C and Fortran char interchange.  As I recall, on all _recent_ R versions that is defined.  You likely have an ancient one.  So your 'Fix available?":   Upgrade, maybe?   Or use an older package on an older system.

**Comment by eddelbuettel** [comment]
Or just see issues #107 and #112 which are from what I can tell with the little you supplied the same.  So I'll likely close this -- problem is on your end, not ours.  We provide a package in the form CRAN demands _and tests on current systems_.

**Comment by user296** [comment]
Thank you. My R version is a bit old. I'll try the latest version.
