### ISSUE TITLE
Can't install on arm64 (MacOS)

### ISSUE THREAD

**Issue by Scarefaced** [RcppCore/RcppEigen#117]
Hi,

I'm trying to use a package (snowRMM) using RcppEigen, but the installation halts. When i try to install RcppEigen separately the following error-message occurs: 

19 warnings generated.
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/Rcpp/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c init.c -o init.o
clang++ -arch arm64 -std=gnu++14 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o RcppEigen.so RcppEigen.o RcppExports.o fastLm.o init.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0 -L/opt/R/arm64/gfortran/lib -lgfortran -lemutls_w -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.2.0/11.0.0'
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [RcppEigen.so] Error 1
ERROR: compilation failed for package ‘RcppEigen’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppEigen’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/RcppEigen’

Please help as my progress with snowRMM seemingly is halted due to RcppEigen. 

Kind regards

**Comment by eddelbuettel** [comment]
You need to install `gfortran`.  There should be some support posts around, else please ask on `r-sig-mac`.
