### ISSUE TITLE
Undefined symbol: RcppEigen_Eigen_SSE

### ISSUE THREAD

**Issue by brgew** [RcppCore/RcppEigen#120]
Hi,

I want to load RcppEigen from a GitHub clone of the master branch. Running the R devtools command

`> devtools::load_all()  # in the RcppEigen clone directory`

gives, finally, the message

```
Error in dyn.load(dll_copy_file) : 
  unable to load shared object '/tmp/Rtmp8gE2OJ/pkgload4dfc3e6993ef/RcppEigen.so':
  /tmp/Rtmp8gE2OJ/pkgload4dfc3e6993ef/RcppEigen.so: undefined symbol: RcppEigen_Eigen_SSE
```

I suppose I am missing something. Probably in my environment?

I am running R 4.2.2 on Debian Bullseye.

```
> devtools::session_info()
─ Session info --

 setting  value
 version  R version 4.2.2 (2022-10-31)
 os       Debian GNU/Linux 11 (bullseye)
 system   x86_64, linux-gnu
...
```

I appreciate your guidance.

Thank you.

**Comment by eddelbuettel** [comment]
I don't use devtools, and we do not document or recommend it's use. I suggest you use `R CMD build .` followed by the install step.

**Comment by eddelbuettel** [comment]
Can you please provide more details?  The package is 10+ years old and has been tested _daily_ at CRAN on multiple architectures.  The error _will likely be at your end_ but I cannot help with the details (or lack thereof) given.

See https://cloud.r-project.org/web/checks/check_results_RcppEigen.html, I would be happy to share logs from my Ubuntu system but they will look the same.  So feel free to reopen but with pertinent detail.
