### ISSUE TITLE
ORCID ID?

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppEigen#138]
Hi @yixuan it appears that CRAN now enforces Authors@R inside of DESCRIPTION so I am slowly switching to it. (And RcppEigen may need a quick one-line change and upload to accommodate wider BLAS/LAPACK headers, I am currently working on this and may an very minor upload 'soon').  From other packages, I have ORCDI for Doug and Romain (and an open question whether they want them or not in the RcppArmadillo repo) but I didn't find anything for you in the repos of your packages.  Do you have an [ORCID ID](https://www.orcid.org) ? Do you care?  These are not mandatory, but if you have one, or want to create one, let me know and I add it.  Hope all is well.  -- D.

**Comment by eddelbuettel** [comment]
Thanks, and done!  I shipped one tar.gz to CRAN for them to test (while they are "closed", they asked for a microfix) so worst case one release may go out before I add the ORCID but I will add it now to the sources in my repo.

**Comment by yixuan** [comment]
Thanks!

**Comment by eddelbuettel** [comment]
(Sorry, been traveling).  This actually made it to CRAN in a once-more-edited fashion so all our ORCIDs are now visiable at https://cloud.r-project.org/web/packages/RcppEigen/index.html ... but looking at it now I see that only two of the four render correctly.  I must have missed a small detail.  Will fix.
