### ISSUE TITLE
RcppEigen.package.skeleton fails to find pkgKitten::kitten

### ISSUE THREAD

**Issue by grantbrown** [RcppCore/RcppEigen#21]
Fixed in [512102](https://github.com/grantbrown/RcppEigen/commit/5121022ed35a04180d589fc6cebfdc12106784a4), I can submit a pull request if you think this is adequate. 

On Linux Mint 17.1, when calling RcppEigen.package.skeleton, I receive the following error:

    Calling kitten to create basic package.
    Error in value[[3L]](cond) : error while calling `kitten`

The original error message is not provided, but digging in a bit further it seemed that R couldn't find the "kitten" function, despite calling requireNamespace("pkgKitten"), as the pkgKitten namespace wasn't attached. The commit mentioned above stores skelFunUsed and skelFunName separately, instead of trying to infer the function from the name.

**Comment by eddelbuettel** [comment]
Darn.  By symmetry RcppArmadillo has the same issue, and I _just_ made a release yesterday.

**Comment by eddelbuettel** [comment]
The suggested patch is great.  I'll apply, with credit -- and a big Thank You!

**Comment by grantbrown** [comment]
No problem, glad it was helpful!
