### ISSUE TITLE
Deprecated warnings with -std=c++11

### ISSUE THREAD

**Issue by drjdn** [RcppCore/RcppEigen#26]
Not sure if this qualifies as an issue but when I compile the following example I get a bunch of deprecated warnings when using the gcc -std=c++11 flag (added to Makevars with PKG_CXXFLAGS):

```cpp
#include <Rcpp.h>
using namespace Rcpp;
#include <RcppEigen.h>

// [[Rcpp::depends(RcppEigen)]]

using Eigen::Map;                       // 'maps' rather than copies
using Eigen::MatrixXd;                  // variable size matrix, double precision
using Eigen::VectorXd;                  // variable size vector, double precision
using Eigen::SelfAdjointEigenSolver;    // one of the eigenvalue solvers

// [[Rcpp::export]]
List getEigenValues(Map<MatrixXd> M) {
  SelfAdjointEigenSolver<MatrixXd> es(M);
  auto M1 = M * M;
  List ret;
  ret["values"]=es.eigenvalues();
  ret["vectors"]=es.eigenvectors();
  ret["prod"] = M1;
  return ret;
}
```

The code does compile and works as expected but there are some warnings about 'std::binder2nd’.  Again, not sure if this qualifies as an issue as the code does run properly.

Best regards,
Jason

**Comment by eddelbuettel** [comment]
i)  To make your post more readable, see [here](https://guides.github.com/features/mastering-markdown/) and mark it as c++
ii) To make your report of what you suspect to be an error more meaningful, include the error message.
iii) Did you mean `-std=c++11` ?  There is no such thing as `-std=c++` or did you call `gcc` ?

**Comment by drjdn** [comment]
i)  Hopefully that is better, thanks for the info.
ii) I can provied the full output if you would like but they are several of the following form (this is the first but the subsequent are the similar, i.e. in regards to binder2nd being deprecated):

/usr/local/R/lib/R/library/RcppEigen/include/Eigen/src/Core/Functors.h:973:28: warning: ‘template<class _Operation> class std::binder2nd’ is deprecated [-Wdeprecated-declarations]
  struct functor_traits<std::binder2nd<T> >

iii)  Yes, I've modified the above.  Hopefully it is now clear.

**Comment by eddelbuettel** [comment]
Much better :)

Now ... look with squinting eyes at the message.  It comes form _Eigen_.   Which is code I don't write bu just included.   And we're currently current (or unaware of a new release).   So maybe you want to them?

Any objections to me closing this?

**Comment by drjdn** [comment]
No objections, please close.  Indeed, the problem is with Eigen.  Guess they don't fully conform to the C++11 standard (although only warnings and not compile time failure).  The following code gives the same error message:

```cpp
#include <Eigen/Core>

using Eigen::MatrixXd;                  // variable size matrix, double precision
using Eigen::Matrix3d;                  // variable size matrix, double precision

int main() {
  MatrixXd M(3,3);
  M << (Matrix3d() << 1, 2, 3, 4, 5, 6, 7, 8, 9).finished();
  MatrixXd M1 = M * M;
  return 0;
}
```
I thought it was the use of 'auto'...  I find template based code errors a bit convoluted;  I'll squint a little more closely next time.  Sorry for the noise.

**Comment by eddelbuettel** [comment]
No worries.

**Comment by drjdn** [comment]
Update:  Just to be thorough I've tested with Eigen3.3-beta1 and the warnings no longer exist.  So any this issue will go away with the next upstream release.

**Comment by eddelbuettel** [comment]
:+1:
