### ISSUE TITLE
Compilation failed on R-devel

### ISSUE THREAD

**Issue by jangorecki** [RcppCore/RcppEigen#31]
```sh
docker run -it --net=host rocker/drd R
```
```r
install.packages("RcppEigen")
#...
#trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.3.tar.gz'
#...
#trying URL 'https://cran.rstudio.com/src/contrib/RcppEigen_0.3.2.8.1.tar.gz'
#...
#/usr/bin/ld: cannot find -llapack
#/usr/bin/ld: cannot find -lblas
#collect2: error: ld returned 1 exit status
#/usr/share/R/share/make/shlib.mk:6: recipe for target 'RcppEigen.so' failed
#make: *** [RcppEigen.so] Error 1
#ERROR: compilation failed for package ‘RcppEigen’
```

**Comment by eddelbuettel** [comment]
Not a valid report given [the CRAN report](https://cloud.r-project.org/web/checks/check_results_RcppEigen.html).

Rocker containers are toolkits.  If they don't suit you, don't use this.  This report is pretty astonishing for an experienced user like you.

**Comment by jangorecki** [comment]
Yes, it doesn't contain all the details, or even a comment. Still it is fully reproducible, allowing to get any info. I've found it compiling fine in when using Rdevel (`RD`).
