### ISSUE TITLE
Parallel Matrix Multiply

### ISSUE THREAD

**Issue by alexvpickering** [RcppCore/RcppEigen#35]
Is it possible to perform parallel matrix multiplications with `RcppEigen`? I am achieving faster (~2x) single-core results with `RcppEigen`  as compared to `%*%` but as I have 8 cores, and `%*%` uses all them, `%*%` ends up being faster (by about 3x).

Here is my test.cpp file:

```
// [[Rcpp::depends(RcppArmadillo, RcppEigen)]]

#include <RcppArmadillo.h>
#include <RcppEigen.h>

// [[Rcpp::export]]
SEXP armaMatMult(arma::mat A, arma::mat B){
    arma::mat C = A * B;

    return Rcpp::wrap(C);
}

// [[Rcpp::export]]
SEXP eigenMatMult(Eigen::MatrixXd A, Eigen::MatrixXd B){
    Eigen::MatrixXd C = A * B;

    return Rcpp::wrap(C);
}

// [[Rcpp::export]]
SEXP eigenMapMatMult(const Eigen::Map<Eigen::MatrixXd> A, Eigen::Map<Eigen::MatrixXd> B){
    Eigen::MatrixXd C = A * B;

    return Rcpp::wrap(C);
}
```

And the results I am getting:

```
library(Rcpp)
sourceCpp("test.cpp")

X_test <- matrix(rnorm(4112*23050), nrow = 4112)
W1     <- matrix(rnorm(23050*2500), ncol = 2500)

system.time(res <- eigenMatMult(X_test, W1))
user  system elapsed 
29.536   0.552  30.147 

system.time(pres <- X_test %*% W1)
user  system elapsed 
71.600   4.464   9.937
```

**Comment by eddelbuettel** [comment]
"Maybe". I am more familiar with Armadillo than with Eigen, and the former uses external LAPACK/BLAS which _can_ use multiple core. Eigen traditionally did its own thing so it may not.

But you a) may want to look into using the rbenchmark or microbenchmark packages and b) subscribe to and post on the rcpp-devel list as this more of an open-ended question than a straight feature request or bug report.  So I suggest we close this.

**Comment by alexvpickering** [comment]
Thanks for the quick response Dirk. Yes, I believe the `armaMatMult` above was using multiple cores, but it wasn't considerably faster than `%*%`.  I am just a little surprised/annoyed that matrix multiplication in R is so much slower than python (as shown [here](http://stackoverflow.com/questions/38602521/make-matrix-multiplication-in-r-as-fast-as-in-python). From my limited knowledge, I was thinking a parallel implementation of Eigen's matrix multiplication would bridge part of the gap.

**Comment by eddelbuettel** [comment]
I just sent you this link on SO: https://eigen.tuxfamily.org/dox/TopicMultiThreading.html

In general, don't cross post.
