### ISSUE TITLE
Update to Eigen 3.2.9

### ISSUE THREAD

**Issue by bob-carpenter** [RcppCore/RcppEigen#36]
We'd like to use Eigen 3.2.9 (released 18.07.2016) for RStan because they've made private members of the unsupported matrix exponential class protected, which we need to extend them to our autodiff types for Stan (so we can provide differentiable steady-state solutions to systems of diff eqs). 

I don't know what Eigen's or RcppEigen's schedules are for the stable version of 3.3.0, but that would also work for us assuming they roll in 3.2.9 changes---we've already updated Stan's integration to deal with all the changes in 3.3.0.  It'll be at least a month or two from now until we're ready to roll out matrix exponentials.

**Comment by eddelbuettel** [comment]
A new release mostly consists of carefully diff'ing what was in the last one, and then checking what goes into the next.  As @yixuan and I are a little tied, could you maybe lead the charge with a PR?  

Else we will try to get to it but it could take days or longer...

I cannot speak to 3.3.0. That is Eigen upstream, and I don't have a close upstream/downstream relationship with them.

**Comment by bob-carpenter** [comment]
We could do that (probably not me, because I barely understand R from a user perspective, much less from a developer perspective), but we're in no rush and I'm not sure what you need for the diff.  Are there just sets of unit tests somewhere we can run?

**Comment by eddelbuettel** [comment]
That is part of running `R CMD check ...name_of_tarball...`, yes.  Talk to some local R users (of which you have several) or wait for us.  Ping us weekly if there is no progress.

If you're in no hurry we can _probably_ get to it.

**Comment by bgoodri** [comment]
No rush but I can help if necessary.

**Comment by yixuan** [comment]
Hi All, I could help to make an update to `RcppEigen` later.

**Comment by bob-carpenter** [comment]
Thanks much (and sorry to clutter your issue).

**Comment by yixuan** [comment]
Great. Thank you Dirk!

**Comment by eddelbuettel** [comment]
My pleasure -- but thanks goes to you for the heavy lifting, and to @coatless for an extension.  I just applied some spit and polish at the end (and clarified things during the CRAN admission process).
