### ISSUE TITLE
DT_DIR not defined

### ISSUE THREAD

**Issue by idiot-z** [RcppCore/RcppEigen#38]
Hi

When trying to install another R package on cygwin I ran into the error:
`path/to/R/library/RcppEigen/include/unsupported/Eigen/src/SparseExtra/MatrixMarketIterator.h:182:34: error: ‘DT_DIR’ was not declared in this scope`

Which, according to the note on that line, was a foreseen issue..
Any hint on how to make this work?
Thanks!

**Comment by eddelbuettel** [comment]
R itself is not supported via Cygwin, so you have a problem with your starting assumption.

RcppEigen builds fine on Windows _in the normal, documented and supported way_.  So I think we should close this.

**Comment by idiot-z** [comment]
thanks for your politeness..
I was just asking for some help, sorry for trying.

**Comment by eddelbuettel** [comment]
Just making sure your expectations are correctly calibrated.  

You may well end up getting this working on Cygwin, just don't expect help from us -- the R Core makes the call of what platforms they support or not.  And Cygwin is out of scope.

Windows works fine, but you **must** use the Rtools compiler.

**Comment by yixuan** [comment]
May I ask the versions of the software (compiler/cygwin/Eigen) involved?

**Comment by yixuan** [comment]
@eddelbuettel That's actually related to our "manual patch" on Eigen, which is a system-dependent macro.

**Comment by eddelbuettel** [comment]
I just ran `ag` over and also found just one line I meant to chase (but got distracted).  But that does not invalidate my point: Cygwin is simply not a platform we will ever test on...

**Comment by eddelbuettel** [comment]
The code is [here](https://github.com/RcppCore/RcppEigen/blob/master/inst/include/unsupported/Eigen/src/SparseExtra/MatrixMarketIterator.h#L181-L183) and we could support Cygwin as we do with others for as long as it remains clear it is not a fully supported or tested platform...

**Comment by idiot-z** [comment]
I didn't mean to sound as your code is buggy or anything. I only wanted to know if there was a quick fix or hack I could try out.
Maybe starting an official issue was not appropriated.
But thank you! I'll give it a try.

**Comment by yixuan** [comment]
Hi @idiot-z, I'd like to take a look, and that's why I want to ask the versions of your compiler/cygwin/Eigen.

**Comment by idiot-z** [comment]
Hi, sure! tomorrow though. I already left work.

**Comment by eddelbuettel** [comment]
> Maybe starting an official issue was not appropriated.

Au contraire.   And over time we all get better at this.  Ie you could also have grep'ed for missing identifier, seen it was used in one instance which was heavily `#ifdef`'ed, made the changes, tested it (!!) and then sent us pull request.

Don't get me wrong. I am not saying you must do that. But I am saying that this is the spectrum.  

And you were on the other end, just stating you used a (if I may: unsupported) platform and it broke.   Well, there is the money-back guarantee on free software...

**Comment by thirdwing** [comment]
The line causing error is here: https://github.com/RcppCore/RcppEigen/blob/master/inst/include/unsupported/Eigen/src/SparseExtra/MatrixMarketIterator.h#L182

`DT_DIR` should be provided by the `libc` (see http://www.gnu.org/software/libc/manual/html_node/Directory-Entries.html)

I am afraid cygwin doesn't define it. You can try to just comment out that line in `MatrixMarketIterator.h`.

**Comment by eddelbuettel** [comment]
@thirdwing, yes see [my comment from two hours ago](https://github.com/RcppCore/RcppEigen/issues/38#issuecomment-264914580) which had the same link.  We could just add Cygwin as a fifth OS to ignore the test requiring `DT_DIR`.

**Comment by idiot-z** [comment]
So I added `|| defined(__CYGWIN__)` at the end of the `#if !(define(...` line and it compiled. (It then ran into another problem, but that was due to the other R package)

@yixuan, about what you asked
> I want to ask the versions of your compiler/cygwin/Eigen

The compiler is gcc-g++ 5.4.0-1
There's no cygwin version (see [cygwin FAQ](https://cygwin.com/faq/faq.html#faq.what.version)), windows version is Windows 10 Pro
RcppEigen 0.3.2.9.0 (from CRAN)

**Comment by eddelbuettel** [comment]
Yes, plain C++ code "should" work.  

I am not so sure about the other parts of R -- if it were easy to support 100% then R Core would do it -- but I forget the details.   We can clearly add the `#define` here but again, it won't guarantee total bliss on Cygwin.
