### ISSUE TITLE
Status of Eigen 3.3.2

### ISSUE THREAD

**Issue by yixuan** [RcppCore/RcppEigen#41]
I just want to report the current status of updating `RcppEigen` to Eigen 3.3.2. In short, there are a few incompatibilities between the dependent packages of `RcppEigen` and Eigen 3.3. Below is a list of packages that have problems so far:

### BigVAR

[Fixed](https://github.com/wbnicholson/BigVAR/commit/927b0a47cf038d60d9a37739cd250339424664f7) on GitHub

### CorReg

File `rechercheZ.cpp`, line 90-92:
`imaxiter` is a numeric vector, so `imaxiter[0]` is of type "double".
The constructor of Eigen vectors require integer argument, so `imaxiter[0]`
should be changed to `static_cast<int>(imaxiter[0])`.

File `rechercheZ_rejet.cpp`, line 60-62: Same as above.

File `rechercheZ_relax.cpp`, line 58-60: Same as above.

File `rechercheZ_sparse_relax.cpp`, line 66-68: Same as above.

### oem

[Fixed](https://github.com/jaredhuling/oem/commit/6bc3bdb75cfedcb913f38e999adbb066babdb133) on GitHub

**Update 03/22**: Already fixed in recent CRAN version.

### OpenMx

Waiting [bug](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1380) to be fixed.

**Update 03/22**: The code is now able to compile, but has a new runtime error.

### TDA

In Eigen 3.3, when one wants to define a new scalar type, one needs to define a new `typedef` named
`Literal`.

`src/CGAL/Sqrt_extension/Eigen_NumTraits.h`, line 31: Add one line `typedef Real Literal;`.

`src/CGAL/Quotient.h`, line 860: Add one line `typedef CGAL::Quotient<NT> Literal;`.

`src/CGAL/Mpzf.h`, line 1136: Add one line `typedef CGAL::Mpzf Literal;`.

`src/CGAL/MP_Float.h`, line 889: Add one line `typedef CGAL::MP_Float Literal;`.

`src/CGAL/Lazy_exact_nt.h`, line 1429: Add one line `typedef CGAL::Lazy_exact_nt<ET> Literal;`.

`src/CGAL/Interval_nt.h`, line 1269: Add one line `typedef CGAL::Interval_nt<b> Literal;`.

`src/CGAL/Gmpz.h`, line 216: Add one line `typedef CGAL::Gmpz Literal;`.

`src/CGAL/Gmpq.h`, line 142: Add one line `typedef CGAL::Gmpq Literal;`.

### TMB

A bit more complicated. The package depends on another library that has compatibility issues with Eigen 3.3, and I'm trying to find a way to fix it.

I think we need to wait for all bugs being fixed before we can submit the updated `RcppEigen` to CRAN.

**Update 02/18**: Issues of TMB have been [fixed](https://github.com/kaskr/adcomp/blob/master/TMB/NEWS#L14) by the author.

**Comment by eddelbuettel** [comment]
You are, once again, amazing.  We just had a much, much smaller transition issue with Rcpp, and even that took time to sort out (with Christmas Xmas and New Year having a little to do with the delay).

If we sort all this out, we can (and should!!) present this as the plan to CRAN.  Keeping up with upstream is important, and sometimes we just have to make small change.

These all look pretty reasonably, with the possible exception of TMB.  Keep us posted, and let me know if I can help (eg by running tests for which I am set up).

**Comment by yixuan** [comment]
Oh that's so nice of you. When everything is ready I do need your help to run another round of tests to make sure it works in different platforms. :-)

**Comment by yixuan** [comment]
Sorry for the long wait. Here is the update:

I've already pulled the newest version of Eigen to my own [branch](https://github.com/yixuan/RcppEigen/tree/Eigen3.3.3) that also incorporates the recent changes from 0.3.2.9.1. This version should have already fixed all the critical compilation issues on existing packages, and I will start to send emails to the maintainers of the packages above to let them submit an update.

Now there is another complication. The `OpenMx` package compiles well but brings a runtime error. I've sent an issue at their repository and see if it can be fixed.

**Comment by eddelbuettel** [comment]
Did you see that [OpenMX just upgraded](http://dirk.eddelbuettel.com/cranberries/2017/03/22#OpenMx_2.7.9) ?   Does that help?

**Comment by yixuan** [comment]
Yes. That's the version I used for checking.

**Comment by eddelbuettel** [comment]
CRAN mostly just wants us to be proactive and to reach out.  We can wait for OpenMX.

What about CorReg?

**Comment by yixuan** [comment]
I'll send emails to them later.

**Comment by eddelbuettel** [comment]
How did it go?

**Comment by yixuan** [comment]
Hi Dirk, sorry for the delay -- I was tied up with some other duties.
I've just run another round of check, and the problematic packages are listed below:

- CorReg: Email sent, with no response from the author
- TDA: Author agreed to submit an update, but not yet
- OpenMx: Run-time error, but the author could not reproduce the error (https://github.com/OpenMx/OpenMx/issues/18)
- treatSens: Did not pass [CRAN checks](https://cran.r-project.org/web/checks/check_results_treatSens.html)
- rstanarm: Did not pass [CRAN checks](https://cran.r-project.org/web/checks/check_results_rstanarm.html)

**Comment by eddelbuettel** [comment]
treatSens also crossed my path, that package seems to have issues of its own.
Cannot speak to the others.

At some point you need to make a call.  You can continue to wait on other packages, and possible wait forever, or you decide it is time.   CRAN just threw eight packages off.

**Comment by yixuan** [comment]
I see. I'll have a last try to contact those authors and we may finalize this by next week.

**Comment by eddelbuettel** [comment]
By the way, the set of CorReg, TDA, OpenMx, rstanarm passed 3 out 3 tests I ran against Rcpp this week

**Comment by yixuan** [comment]
That's correct. They are compatible with Eigen 3.2.x but not with Eigen 3.3.y.

**Comment by bgoodri** [comment]
I just installed the Eigen3.3.3 branch, and the rstanarm package is fine.

**Comment by yixuan** [comment]
@eddelbuettel I haven't received any updates from the maintainers of those packages, so probably we can finalize this version and submit to CRAN. If there is no other concern, I'll create a PR later.

**Comment by kaskr** [comment]
@yixuan @eddelbuettel 
When compiling with `CXX = g++ -pedantic -Wall` (ubuntu 16.04) I get some new compiler warnings with Eigen 3.3 that did not show up with Eigen 3.2.

`devtools:::install_github("RcppCore/RcppEigen")`

compiles cleanly without warnings while

`devtools:::install_github("yixuan/RcppEigen", ref="Eigen3.3.3")`

produces lots of these:

```
../inst/include/Eigen/src/Core/arch/CUDA/Half.h:122:46: warning: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
   EIGEN_DEVICE_FUNC EIGEN_EXPLICIT_CAST(long long) const {
                                              ^
../inst/include/Eigen/src/Core/arch/CUDA/Half.h:42:48: note: in definition of macro ‘EIGEN_EXPLICIT_CAST’
 #define EIGEN_EXPLICIT_CAST(tgt_type) operator tgt_type()
                                                ^
```

Perhaps worth fixing before submitting to CRAN ?

**Comment by eddelbuettel** [comment]
The standard fix for that is to compile as a C++11 program.

**Comment by yixuan** [comment]
@kaskr I'll send a report to Eigen. It should be easy to fix by adding some `#ifdef` macros.

**Comment by yixuan** [comment]
@eddelbuettel I haven't heard from Gael, but I'm able to give a quick fix. We can either wait for updates from Eigen, or submit RcppEigen to CRAN first using my patch, and then synchronize to upstream in the future. Which one do you prefer?

**Comment by eddelbuettel** [comment]
I'd say local patches are perfectly fine for as long as we don't forget that we applied them :)    We have done this before.   Synchronizing with upstream is nice too, but we may not want to wait "forever".  Maybe it is time for 3.3.2.   What do you think is best?

**Comment by yixuan** [comment]
Great. I've applied the local patch already. Let me launch another round of checks before I submit the PR.

**Comment by eddelbuettel** [comment]
Why don't you submit the PR, and I will test here too?

**Comment by eddelbuettel** [comment]
Or conversely, maybe I just fetch it from your fork...

**Comment by yixuan** [comment]
Oh sure. That will be nicer.

**Comment by eddelbuettel** [comment]
No worries, it's running already :)

**Comment by eddelbuettel** [comment]
I just pushed a small commit into your PR to update `.travis.yml`.

**Comment by eddelbuettel** [comment]
Need to restart it as I was running into the R 3.4.0 upgrade issue where packages containing `.Fortran()` and `.C()` (and that had been installed under older R versions) would not find their compiled routines.

**Comment by eddelbuettel** [comment]
Ok -- I got eight failures.  The first was a build failure in CorReg; all others seven other seem like side effects from not-yet-having-rebuilt all recommended packages.  I will do that and restart.

**Comment by yixuan** [comment]
Great. Thanks!

**Comment by eddelbuettel** [comment]
Just finished run two, and [committed to rcpp-logs](https://github.com/RcppCore/rcpp-logs/commit/716cc13c66ad89a15de2b8eb90a6bce090d9180d).

I think we're fine, but I would of course need to know what you think.  CorReg still has an issue, and OpenMx goes belly-up numerically in one test.  That may not be us in either case.

**Comment by yixuan** [comment]
I have listed the solution for CorReg in the very beginning but unfortunately I was unable to get any reply from the author. I've also told OpenMx our check result (https://github.com/OpenMx/OpenMx/issues/18) and let's see how they decide.

**Comment by yixuan** [comment]
Just got a reply from Joshua there and I think we are good to go and submit.

**Comment by eddelbuettel** [comment]
I think I'll roll it up tomorrow morning and send it to Vienna.
