### ISSUE TITLE
RcppEigen_Eigen_SSE has no calling parameters

### ISSUE THREAD

**Issue by tjeerdijk** [RcppCore/RcppEigen#44]
last line of lmBenchmark.R:
> .Call("RcppEigen_Eigen_SSE", FALSE, PACKAGE="RcppEigen")
Error in .Call("RcppEigen_Eigen_SSE", FALSE, PACKAGE = "RcppEigen") : 
  Incorrect number of arguments (1), expecting 0 for 'RcppEigen_Eigen_SSE'

Correct call:
> .Call("RcppEigen_Eigen_SSE", PACKAGE="RcppEigen")
[1] TRUE

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RcppGSL_0.3.2             RcppArmadillo_0.7.800.2.0 RcppEigen_0.3.3.3.0       rbenchmark_1.0.0         

loaded via a namespace (and not attached):
[1] compiler_3.4.0  Matrix_1.2-9    tools_3.4.0     Rcpp_0.12.11    grid_3.4.0      lattice_0.20-35

**Comment by eddelbuettel** [comment]
So you are suggesting to drop argument `FALSE` ?  Can do.

**Comment by tjeerdijk** [comment]
Hi Dirk,

Yup, just drop the argument. It’s a really minor issue.

Take care from Tjeerd

**Comment by eddelbuettel** [comment]
Yes, that is clearly a copy-and-paste-oh error from the preceding line.  The whole file needs updating though.

**Comment by tjeerdijk** [comment]
Hi Dirk,

Thx. That was fast.

I hope you don't mind my asking another question: is it hard to use one of the unsupported modules of RcppEigen, in particular the LevenbergMarquardt one (and I know there a package in R that directly makes the LM from minpack available)?

Take care from Tjeerd

**Comment by eddelbuettel** [comment]
Not sure.  May actually just work -- we carry the headers over as a convenience, but they should be fully useable.

But personally speaking I might still go to something like [nloptr](https://cran.r-project.org/package=nloptr) to do optimization.

**Comment by tjeerdijk** [comment]
Hi Dirk,

The reason for looking into the LM version in Eigen is that we use Eigen in OpenMS (opens.de). A bachelor student (working in R) will pilot an new normalisation algorithm. Using the LM from Eigen will make integration into OpenMS easier, so we are more or less tied.

Thx for the reference to nloptr, I did’t know about this library. Will use it is my own research!

Take care from Tjeerd
