### ISSUE TITLE
RcppEigen.so: file too short

### ISSUE THREAD

**Issue by RoyalTS** [RcppCore/RcppEigen#47]
I'm an absolute noob when it comes to build issues so apologies in advance should the solution to this be obvious.

Trying to install `RcppEigen` yields the following error:

    trying URL 'https://cloud.r-project.org/src/contrib/RcppEigen_0.3.3.3.1.tar.gz'
    Content type 'application/x-gzip' length 1627022 bytes (1.6 MB)
    ==================================================
    downloaded 1.6 MB
    
    * installing *source* package 'RcppEigen' ...
    ** package 'RcppEigen' successfully unpacked and MD5 sums checked
    ** libs
    g++  -I/farmshare/software/free/r/R-3.4.2/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -g -O2  -c RcppEigen.cpp -o RcppEigen.o
    g++  -I/farmshare/software/free/r/R-3.4.2/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -g -O2  -c RcppExports.cpp -o RcppExports.o
    g++  -I/farmshare/software/free/r/R-3.4.2/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -g -O2  -c fastLm.cpp -o fastLm.o
    gcc -std=gnu99 -I/farmshare/software/free/r/R-3.4.2/include -DNDEBUG  -I"/afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include   -fpic  -g -O2  -c init.c -o init.o
    g++ -shared -L/farmshare/software/free/r/R-3.4.2/lib -L/usr/local/lib -o RcppEigen.so RcppEigen.o RcppExports.o fastLm.o init.o -llapack -lf77blas -latlas -lgfortran -lm -lquadmath -L/farmshare/software/free/r/R-3.4.2/lib -lR
    installing to /afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/libs
    ** R
    ** inst
    ** preparing package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** installing vignettes
    ** testing if installed package can be loaded
    Error: package or namespace load failed for 'RcppEigen' in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object '/afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/libs/RcppEigen.so':
      /afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen/libs/RcppEigen.so: file too short
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing '/afs/.ir.stanford.edu/users/t/o/tobiass/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen'
    
    The downloaded source packages are in
    	'/tmp/Rtmpk2ViVr/downloaded_packages'
    Warning message:
    In install.packages("RcppEigen") :
      installation of package 'RcppEigen' had non-zero exit status

System Info:
    
    > sessionInfo()
    R version 3.4.2 (2017-09-28)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Ubuntu 14.04.5 LTS
    
    Matrix products: default
    BLAS: /usr/lib/atlas-base/libf77blas.so.3.0
    LAPACK: /usr/lib/lapack/liblapack.so.3.0
    
    locale:
    [1] C
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base
    
    loaded via a namespace (and not attached):
    [1] compiler_3.4.2 tools_3.4.2

    ~$ gcc -v
    Using built-in specs.
    COLLECT_GCC=gcc
    COLLECT_LTO_WRAPPER=/software/free/gcc/bin/../libexec/gcc/x86_64-pc-linux-gnu/6.2.0/lto-wrapper
    Target: x86_64-pc-linux-gnu
    Configured with: ./configure --prefix=/farmshare/software/free/gcc/
    Thread model: posix
    gcc version 6.2.0 (GCC)

**Comment by eddelbuettel** [comment]
Looks like an entirely local problem with your file system.  Talk to you system admins, maybe?

**Comment by eddelbuettel** [comment]
Also, for completeness, as you seem to be able to mix newer packages (gcc 6.2.0, R 3.2.4) with an older distro: there _is_ r-cran-rcppeigen.

**Comment by RoyalTS** [comment]
Turned out to be a stupid mistake on my part. Apologies for having bothered you!

**Comment by eddelbuettel** [comment]
That's ok: 

![image](https://user-images.githubusercontent.com/673121/33625079-12c13a86-d9bc-11e7-9fb2-15318ab3e55a.png)

But what _was_ the error?  Any teachable moment here?

**Comment by RoyalTS** [comment]
None too glorious: I had simply run out of disk space without that causing an error with a message specific enough for me to recognize it.

**Comment by eddelbuettel** [comment]
That would do it indeed.
