### ISSUE TITLE
Update Frequency?

### ISSUE THREAD

**Issue by cdeterman** [RcppCore/RcppEigen#48]
I was wondering how often the 'newest' Eigen headers are ported in to this package?  As what usually happens, I am dealing with GPU related problems and I noticed one pull request on the [eigen bitbucket](https://bitbucket.org/eigen/eigen/pull-requests/311/eigen-compilation-with-nvcc/activity) website that addressed the problem (quite minor in this case).  I saw that it was merged back in May 2017 but the change isn't reflected in RcppEigen.  Was a new 'official' release not provided by the Eigen authors perhaps?  

I don't mean to push, as again this issue is quite minor in this instance.  I am only curious how/when you decide to update the headers herein from the Eigen source.

**Comment by eddelbuettel** [comment]
Of late, this mostly relied on Yixuan _really carefully_ preparing new releases and handing them to me more or less ready and on a silver platter.  But he and I are busy so we let 3.3.4 slip.

The changes are small, generally, and go back to things @dmbates needed/added for lme4.  If you start from backing out diffs from our 0.3.3.3.1 to their 3.3.3, you should be able to prepare a 0.3.3.4.0 for us :)

**Comment by yixuan** [comment]
Let me prepare an update this weekend.

**Comment by yixuan** [comment]
@cdeterman The patch you mentioned actually has not been ported to the 3.3 branch of Eigen. It was in the "default" branch, but I have manually patched it for you in #49 .

**Comment by cdeterman** [comment]
@yixuan excellent, thank you for your efforts.

**Comment by eddelbuettel** [comment]
And it is sitting in incoming at CRAN now.
