### ISSUE TITLE
'Compilation failed' error during installation

### ISSUE THREAD

**Issue by Yiyio** [RcppCore/RcppEigen#53]
Hi,

Just wondering if anyone might know the reason for this error. I am using a pretty freshly installed ubuntu xenial 16.04 on an AWS instance (t2 micro so only 1GB of RAM). My g++ version is 5.4.0

It takes quite long before the compilation error appears.

```
> install.packages('RcppEigen')
Installing package into ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/RcppEigen_0.3.3.4.0.tar.gz'
Content type 'application/x-gzip' length 1631870 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘RcppEigen’ ...
** package ‘RcppEigen’ successfully unpacked and MD5 sums checked
** libs
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -I../inst/include -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppEigen.cpp -o RcppEigen.o
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -I../inst/include -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++  -I/usr/share/R/include -DNDEBUG  -I"/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -I../inst/include -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fastLm.cpp -o fastLm.o
virtual memory exhausted: Cannot allocate memory
/usr/lib/R/etc/Makeconf:168: recipe for target 'fastLm.o' failed
make: *** [fastLm.o] Error 1
ERROR: compilation failed for package ‘RcppEigen’
* removing ‘/home/ubuntu/R/x86_64-pc-linux-gnu-library/3.4/RcppEigen’

The downloaded source packages are in
        ‘/tmp/RtmphYSiGQ/downloaded_packages’
Warning message:
In install.packages("RcppEigen") :
  installation of package ‘RcppEigen’ had non-zero exit status
```

**Comment by dselivanov** [comment]
Don't know about this particular problem, but what I faced -  applications which use Eigen taken a lot of ram to compile. So I was not able to compile my packages on machine with 1gb of ram. Which is pity.

**Comment by eddelbuettel** [comment]
We answered similar questions before, and _also note you can get precompiled r-cran-rcppeigen_ from several places including the distribution itself (though possibly dated from the release) as well as current backports from [Michael's PPA](https://launchpad.net/~marutter/+archive/ubuntu/c2d4u).

So I am closing this.

**Comment by Yiyio** [comment]
@dselivanov thanks, this turned out to be the case

**Comment by eddelbuettel** [comment]
As I said, you don't even _need to_ as RcppEigen exists precompiled for that Ubuntu version.

And yes, C++ requires some RAM.

**Comment by dselivanov** [comment]
@eddelbuettel but still even if you have binary installation and want to build pkg which rely on RcppEigen you will face same issue, won't you? I googled quite a bit, but didn't find any solution/workaround. So for now I stick to machines/containers with 2gb+ of ram (or using prebuild container images).

**Comment by eddelbuettel** [comment]
Correct.  The real issue are the Eigen (and Boost and ...) headers.  But the principle holds:  Michael's PPA has 3000+ packages so people who are stuck may be able to resort to binaries.
