### ISSUE TITLE
Build logs

### ISSUE THREAD

**Issue by jrowen** [RcppCore/RcppEigen#57]
I'm running into an issue with a Travis CI Docker build that includes `RcppEigen` whereby the Travis log is filling up with build output from the package.  You can see this by taking a look at the build output [shown here](https://travis-ci.org/jrowen/dcaret/builds/385968773).

I was running a command similar to the one below to install the package.
```
RUN install2.r --error \
    ...
    RcppEigen \
    ...
```
Is there a better way to install the package or suppress the build output?

**Comment by eddelbuettel** [comment]
Read the ChangeLog: https://github.com/RcppCore/RcppEigen/blob/master/ChangeLog#L24-L27
(and I had thought I had added another comment somewhere ....)

You need to re-instrument the compiler to not warn by e.g. `echo`-ing a `CXXFLAGS=...` setting to `~/.R/Makevars`.

Not really our problem and fault but CRAN Policy. Sorry.   

Otherwise:  use `r-cran-rcppeigen` prebuilt.

**Comment by eddelbuettel** [comment]
The second comment was even more visible here: https://github.com/RcppCore/RcppEigen/blob/master/inst/NEWS.Rd#L19-L20

**Comment by eddelbuettel** [comment]
Had a quick look at `dcaret`. I think you are doing two things in a way that could be improved:
- "hadleyverse" is outdated; Carl now call his main container for this "tidyverse"
- "r-cran-rcppeigen" _definitely_ should be used as a binary

I'll try to write a blog post about "does CRAN package 'foo' exists as a 'r-cran-foo' binary deb ?".  We have answers -- I particularly like my r-apt containers.  Ie:

```sh
edd@rob:~$ docker run --rm -ti rocker/r-apt:trusty bash -c 'apt-get update && apt-cache policy r-cran-rcppeigen'
Get:1 http://ppa.launchpad.net trusty InRelease [15.4 kB]
Get:2 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
Ign http://archive.ubuntu.com trusty InRelease
Get:3 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
Hit http://archive.ubuntu.com trusty-backports InRelease
Get:4 http://ppa.launchpad.net trusty InRelease [15.4 kB]
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.ubuntu.com trusty Release
Get:5 http://ppa.launchpad.net trusty/main amd64 Packages [757 kB]
Get:6 http://archive.ubuntu.com trusty-updates/universe Sources [253 kB]
Get:7 http://archive.ubuntu.com trusty-updates/main amd64 Packages [1,344 kB]
Get:8 http://archive.ubuntu.com trusty-updates/restricted amd64 Packages [21.4 kB]
Get:9 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [586 kB]
Get:10 http://archive.ubuntu.com trusty-updates/multiverse amd64 Packages [16.0 kB]
Hit http://archive.ubuntu.com trusty-backports/main amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-backports/multiverse amd64 Packages
Get:11 http://security.ubuntu.com trusty-security/universe Sources [88.8 kB]
Get:12 http://security.ubuntu.com trusty-security/main amd64 Packages [919 kB]
Get:13 http://security.ubuntu.com trusty-security/restricted amd64 Packages [18.1 kB]
Get:14 http://security.ubuntu.com trusty-security/universe amd64 Packages [290 kB]
Get:15 http://security.ubuntu.com trusty-security/multiverse amd64 Packages [4,727 B]
Hit http://archive.ubuntu.com trusty/universe Sources
Get:16 http://ppa.launchpad.net trusty/main amd64 Packages [9,157 B]
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/multiverse amd64 Packages
Fetched 4,470 kB in 19s (229 kB/s)
Reading package lists... Done
r-cran-rcppeigen:
  Installed: (none)
  Candidate: 0.3.3.4.0-1cran1ppa0trusty0
  Version table:
     0.3.3.4.0-1cran1ppa0trusty0 0
        500 http://ppa.launchpad.net/marutter/c2d4u/ubuntu/ trusty/main amd64 Packages
     0.3.2.0.2-2 0
        500 http://archive.ubuntu.com/ubuntu/ trusty/universe amd64 Packages
edd@rob:~$
```

showing you that eg for Trusty (ie what Travis CI runs) we have 0.3.2.0-2 in the distro and the current 0.3.3.4.0 in the Rutter PPA.

**Comment by jrowen** [comment]
Thanks for the pointers, I'll make some updates and try again.  Interestingly, this seems to be Travis issue, as the Docker Hub build worked fine.
