### ISSUE TITLE
Bug in Eigen::SparseMatrix -> dgCMatrix conversion

### ISSUE THREAD

**Issue by jeffwong-nflx** [RcppCore/RcppEigen#58]
I am using RcppEigen to compute the matrix X^T * X + lambda * I (as in ridge regression) where X is a sparse input matrix. I am able to compute X^T * X in Eigen, however there is an edge case for adding lambda * I. This step modifies the diagonal of the matrix X^T X. If the diagonal had a 0 in it, then you cannot add lambda. Under the hood, X^T * X returns a sparse matrix, so if there is a 0 on the diagonal there is no memory allocated that I can use to add.

In Eigen, the appropriate way to modify a value in a sparse matrix which may not exist yet is to use [.insert](https://eigen.tuxfamily.org/dox/group__SparseQuickRefPage.html). This produces valid Eigen code, but for some reason when the resulting matrix is brought back to R as a dgCMatrix I get the error:

Error in validObject(x) : 
  invalid class “dgCMatrix” object: last element of slot p must match length of slots i and x

Here is a reproducible example. I believe the relevant [wrapper code in RcppEigen](https://github.com/RcppCore/RcppEigen/blob/70d14fc48be807e3f4d3c7f9514d0fa40c33fb50/inst/include/RcppEigenWrap.h#L340) is here, though I don't know what the right solution is.

```
#include <Rcpp.h>
#include <RcppEigen.h>
// [[Rcpp::depends(RcppEigen)]]

using Eigen::Map;
using Eigen::MatrixXd;
using Eigen::VectorXd;
using Eigen::SparseMatrix;
using Eigen::MappedSparseMatrix;
using namespace Rcpp;
using namespace Eigen;

// [[Rcpp::export]]
Eigen::SparseMatrix<double> sparseCrossprod(const Eigen::MappedSparseMatrix<double>& X,
                                            const Eigen::VectorXd& l2penalty) {
  SparseMatrix<double> XtX = X.adjoint() * X;
  
  // R won't understand the returned matrix
  for (int i = 0; i < XtX.rows(); i++) {
    double value = XtX.coeff(i, i);
    Rcout << value << std::endl;
    if (value == 0) {
      XtX.insert(i, i) = 1;
    }
  }
  
  // This will crash
  // XtX += VectorXd::Ones(XtX.rows()).asDiagonal();
  
  // This will crash if there is a 0 on the diagonal
  //VectorXd diag(XtX.diagonal());
  //Rcout << diag << std::endl;
  //XtX.diagonal() = diag + l2penalty;
  
  return XtX;
}


/***R
require(Matrix)

k = 2
N = 100000 * k
p = 10
density = .1

X = cbind(1, rsparsematrix(N, p, density))
l2penalty = c(0, rep(1, p))

X[,5] = 0

foo = sparseCrossprod(X, l2penalty)
*/
```

**Comment by eddelbuettel** [comment]
I can replicate the error, but I won't have time to dig into this.

**Comment by jeffwong-nflx** [comment]
Edit: Note that the error doesn't show up until you try to do something with `foo`. For example none of these operations work

```
foo
as.matrix(foo)
2*foo
```

**Comment by yixuan** [comment]
I can try to take a look.

**Comment by yixuan** [comment]
@jeffwong-nflx 
By the way, did you call the `makeCompressed()` member function on sparse matrices before returning to R? I remember this is a **necessary** step. Could you run the examples again by incorporating this simple fix?

**Comment by eddelbuettel** [comment]
Bingo!  Nice call, @yixuan -- the following works:

```c++
// [[Rcpp::export]]
Eigen::SparseMatrix<double> sparseCrossprod(const Eigen::MappedSparseMatrix<double>& X,
                                            const Eigen::VectorXd& l2penalty) {
  Eigen::SparseMatrix<double> XtX = X.adjoint() * X;
  for (int i = 0; i < XtX.rows(); i++) {
    double value = XtX.coeff(i, i);
    if (value == 0) {
      XtX.coeffRef(i,i) = 1;
    }
  }
  XtX.makeCompressed();
  return XtX;
}
```

**Comment by jeffwong-nflx** [comment]
Thanks, that works!  This is an extremely subtle issue inside [Eigen](https://eigen.tuxfamily.org/dox/group__TutorialSparse.html) and only occurs when you insert new values into the sparse matrix. Would you consider adding this to the RcppEigen vignette to prevent future users from making this error?

> The results of Eigen's operations always produces compressed sparse matrices. On the other hand, the insertion of a new element into a SparseMatrix converts this later to the uncompressed mode.

**Comment by eddelbuettel** [comment]
@yixuan Is there a reason we can't automagically do that when `wrap()` is called ?

**Comment by yixuan** [comment]
I think part of the reason is that `wrap()` receives a constant reference to the sparse matrix, but `makeCompressed()` modifies the object itself.

Eigen documents [here](https://eigen.tuxfamily.org/dox/classEigen_1_1SparseMatrix.html) that
> A call to the function makeCompressed() turns the matrix into the standard compressed format compatible with many library.

So I would say that the responsibility is mostly left to the user.

**Comment by eddelbuettel** [comment]
Sounds good to me.  

And I think with that we can close this as well.
