### ISSUE TITLE
RcppEigen Error GLIBC

### ISSUE THREAD

**Issue by tiagobrc** [RcppCore/RcppEigen#60]
```
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Error: package or namespace load failed for ‘RcppEigen’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/data_alpha/home/trezende/compiled/R-3.4.4/lib64/R/library/RcppEigen/libs/RcppEigen.so':
  /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /data_alpha/home/trezende/compiled/R-3.4.4/lib64/R/library/RcppEigen/libs/RcppEigen.so)
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/data_alpha/home/trezende/compiled/R-3.4.4/lib64/R/library/RcppEigen’
Warning message:
In install.packages("RcppEigen_0.3.2.2.0.tar.gz") :
  installation of package ‘RcppEigen_0.3.2.2.0.tar.gz’ had non-zero exit status
```

Hi, I am having a lot of trouble installing RcppEigen.  I am using a Rehat Linux server ( without root access) and currently using a local R installation. I tried older sources of RcppEigen, but they had a different set of errors. Too many errors.
I have GLIBC_2.23, and GCC 5.5.0 both installed using Linuxbrew. 

I have Makevars file setting to the newer gcc and RcppEigen keeps looking for  /lib64/libc.so.6 instead of the local updated copy. 

Can you help me?
What am I doing wrong?

Thanks.

**Comment by eddelbuettel** [comment]
I suspect you have a problem with your non-standard R installation. Ensure `gcc`, `gfortran`, `g++`, ... all come from the same consistent version that matches your libc, build R with it and you should have no trouble building packages such as RcppEigen.  Mixing and matching generally leads to trouble.

**Comment by tiagobrc** [comment]
So RcppEigen does not care about GLIBC_2.14? This is just an error of incompatibility? I was expecting to just tell R where to look to the right Glibc.

**Comment by eddelbuettel** [comment]
I don't think that is what I said.  If and when you build R, Rcpp, ... consistently it all works.  See for example the hundreds of (publically visible) builds [at Travis CI](https://travis-ci.org/RcppCore/RcppEigen/builds).  Also simply checking out a Docker container (say our `r-base`) should allow you to just install Rcpp and RcppEigen.

So I think the burden of proof is with you, and I suspect your setup may cause you these issues.

**Comment by tiagobrc** [comment]
Hi,

Thanks for the explanation. Ofc I imagine that the problem was on my side. I just thought that could be easily fixed instead of having to build R again from the source which is very time-consuming. And got confused with the error R was throwing on the screen. 

So I need to build R again with a newer version of Glibc, Gcc (2.14+). In my local MacOS everything worked as a charm but I need more computer power. I will see what I can do. 

Thanks!

**Comment by tiagobrc** [comment]
Hi, 

The problem was fixed by removing all linuxbrew compilations. Like you said, by using the same setup used to compile R in the first place. Which is odd because it is GLIBC 2.12 and the error was looking for 2.14+.

Anyway...

Thanks for your time.

**Comment by eddelbuettel** [comment]
Ok if I we close this?
