### ISSUE TITLE
Eigen 3.3.5

### ISSUE THREAD

**Issue by cdeterman** [RcppCore/RcppEigen#63]
I noticed the latest stable release of Eigen 3.3.5 is [available](http://eigen.tuxfamily.org/index.php?title=Main_Page).  When possible I would love to see RcppEigen updated as I believe the changes made in the recent release will address my previous concerns in #50.

**Comment by eddelbuettel** [comment]
Can you possibly take a lead preparing a careful PR in the style of @yixuan excellent work?  

I am still a little charred from the early past when we had multiple sets of patches.  It should be easier now but if you have time the easiest start may be to recreate any possible delta between our 3.3.4 and Eigen upstream 3.3.4.  Oh, and I just checked, we are now so organized that we [actually did just that](https://github.com/RcppCore/RcppEigen/blob/master/patches/eigen-3.3.4.diff) so maybe you can try rolling that diff forward and carefully fold it into 3.3.5?

**Comment by eddelbuettel** [comment]
I put a candidate package together which I am testing now.

**Comment by eddelbuettel** [comment]
But re-reading what @yixuan told you in #50 I am not entirely sure you will find what you had been are looking for in 3.3.5 as the change seems incremental.

**Comment by eddelbuettel** [comment]
It's now in the queue at CRAN and should be available within a day or two.

**Comment by yixuan** [comment]
Thank you Dirk. I didn't get time to make this done, but I'm glad to see it went smoothly to CRAN!

**Comment by eddelbuettel** [comment]
No worries.  This one was pretty easy, though it threw up one spanner for KH with the very package @cdeterman wanted help with.  That error may have been local so all good now.

**Comment by cdeterman** [comment]
Sorry that I fell off after the initial request, away for the holidays.  Thanks to everyone for getting this out.  You were ultimately right @eddelbuettel as the 'half' changes weren't included in this release.  I thought they would  be as they were in the 3.3 branch of the Eigen but it looks like in my haste I didn't notice the modification dates.  I think the changes happened after the release of 3.3.5.  Not sure, I never was able to get on the Eigen mailing list.  Thanks again for the update.

**Comment by eddelbuettel** [comment]
@cdeterman Thanks for the closure on this.   You could go the same route locally and create yourself an alpha RcppEigen 0.3.4.* package -- it's pretty straightforward.
