### ISSUE TITLE
compilation failed due to file unavailabilty

### ISSUE THREAD

**Issue by Sarvaya-Jain** [RcppCore/RcppEigen#64]
Hi, 
I am trying to install boruto package which have dependency on RccpEigen showing error while compilation then I again tried installing only then also same error is popping up. I have tried manual downloading and installing  still the same error seems not able to find RcppEigenForward.h 
Below is error what I am getting

* installing *source* package 'RcppEigen' ...
** package 'RcppEigen' successfully unpacked and MD5 sums checked
** libs
g++ -m64  -I/usr/include/R -DNDEBUG  -I"/home/sarvagya1/R/x86_64-redhat-linux-gnu-library/3.4/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic  -c RcppEigen.cpp -o RcppEigen.o
In file included from ../inst/include/RcppEigen.h:25:0,
                 from RcppEigen.cpp:22:
../inst/include/RcppEigenForward.h:25:20: fatal error: iterator: No such file or directory
compilation terminated.
make: *** [RcppEigen.o] Error 1
ERROR: compilation failed for package 'RcppEigen'
* removing '/home/sarvagya1/R/x86_64-redhat-linux-gnu-library/3.4/RcppEigen'

**Comment by eddelbuettel** [comment]
1. What is your OS and version?
2. What is your compiler version?

The error message is actually that file `iterator` is not found when `RcppEigenForward.h` wants to access it. Your C++ setup may be lacking.  Ever compiled C++ before on that machine?

**Comment by Sarvaya-Jain** [comment]
1. Actually I am trying to install package in server machine and I have installed some other packages like dplyr etc which have c++ dependency.

Os is: linux 2.6.32
 
2. I tried checking the version of gcc installed, I am getting 5.1.0
below is output received:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/5.1.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../gcc_5_1_0_release/configure
Thread model: posix
gcc version 5.1.0 (GCC)

**Comment by eddelbuettel** [comment]
Well:
- What distro?
- Kernel 2.6.32 is very, very old. You may simply have a toolchain that is too old.  
- `gcc` 5.1.0 is fine, you also need `g++` of course.

Looks like you simply do not have the requirements to build. See the [results page at CRAN](https://cran.r-project.org/web/checks/check_results_RcppEigen.html) to confirm that this package builds and tests fine every night on a variety of current versions, and even one release back.

**Comment by eddelbuettel** [comment]
I'll close this is it appears to a simpler user error or misunderstanding.
