### ISSUE TITLE
installation error: object 'pkgInfo' not found

### ISSUE THREAD

**Issue by sefabey** [RcppCore/RcppEigen#66]
I am trying to install RcppEigen on my uni's cluster and I get the following error. I realised this when installing `broom` package but tracked the issue back to `RcppEigen`. I tried looking for object 'pkgInfo' online but not much returned. Is this something I can fix myself (without sudo permission) or should I consult IT service (who can sudo)? Any help is appreciated as I cannot load `RcppEigen`, hence `broom`, hence `tidyverse`.

> install.packages("RcppEigen")
Installing package into ‘/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/RcppEigen_0.3.3.5.0.tar.gz'
Content type 'application/x-gzip' length 1633859 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package ‘RcppEigen’ ...
** package ‘RcppEigen’ successfully unpacked and MD5 sums checked
** libs
icpc  -I"/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/include" -DNDEBUG  -I"/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -xHost  -c RcppEigen.cpp -o RcppEigen.o
icpc  -I"/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/include" -DNDEBUG  -I"/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -xHost  -c RcppExports.cpp -o RcppExports.o
icpc  -I"/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/include" -DNDEBUG  -I"/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -xHost  -c fastLm.cpp -o fastLm.o
icc -std=gnu99 -I"/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/include" -DNDEBUG  -I"/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -xHost  -c init.c -o init.o
icpc -shared -L/usr/local/lib64 -o RcppEigen.so RcppEigen.o RcppExports.o fastLm.o init.o -L/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/lib -lRlapack -L/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/lib -lRblas -lifport -lifcoremt -limf -lsvml -lm -lipgo -lirc -lpthread -lirc_s -ldl
installing to /nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- imp[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  object 'pkgInfo' not found
ERROR: lazy loading failed for package ‘RcppEigen’
* removing ‘/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen’

The downloaded source packages are in
	‘/tmp/RtmppNWEih/downloaded_packages’
Warning message:
In install.packages("RcppEigen") :
  installation of package ‘RcppEigen’ had non-zero exit status

> Sys.info()
                              sysname                               release
                              "Linux"          "3.10.0-693.21.1.el7.x86_64"
                              version                              nodename
"#1 SMP Fri Feb 23 18:54:16 UTC 2018"                                 "cl1"
                              machine                                 login
                             "x86_64"                          "c.c1541911"
                                 user                        effective_user
                         "c.c1541911"                          "c.c1541911"
>

**Comment by eddelbuettel** [comment]
Huh?

**Comment by sefabey** [comment]
Could be a misdiagnosis on my part. I'll consult local staff. Thanks.

**Comment by eddelbuettel** [comment]
The problem is likely the dependency chain. So to diagnose, let's do it one by one.  You started with `broom` so I reckon we have `lme4` here and hence `RcppEigen`.  Check them individually.

Sometimes it is as simple as 'reinstall the package' as the C++ compiler/library changes may induce subtle issues.  Also: what type of cluster?  Any binary packages from Debian or Ubuntu by chance or all from source?

**Comment by sefabey** [comment]
Thanks for offering help to diagnose the problem as I have been pulling my hair the past week. IT support is not available during Xmas break! Such inconvenient time to be having this error!

To provide some background, I must confess this error only started appearing after I did something I should not have done. I've been working on Supercomputing Wales cluster which works on Slurm (I provided some info about the system below but more than happy to provide more if you require). 

```
[c.c1541911@cl1 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.4 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.4"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.4 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.4:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
```

There is a nfshome drive where my .libpaths is located and there is a scratch drive(lustre methinks) where my data and scripts are stored. 
```

> .libPaths()
[1] "/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5"
[2] "/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/library" 

```



```
[c.c1541911@cl1 ~]$ cd /scratch/c.c1541911/muslim_islam_tweets/
[c.c1541911@cl1 muslim_islam_tweets]$ du -hsc *
15T	data
121M	parse_job
32K	src
15T	total
[c.c1541911@cl1 muslim_islam_tweets]$

```

Two days ago, I was processing some batch data on the scratch drive and exporting intermediate results to `.rds` files. I recognised an issue with intermediate `.rds` files and wanted to remove all `.rds` files on my scratch drive and re-process data. Stupidity begins here. Thinking I was in my data folder on the scratch drive, I executed `find . -type f -name '*temp.rds' -delete`. However, apparently, I was on my nfshome drive and I, inadvertently (read stupidly), removed all `.rds` files in my nfshome, hence in my `.libPaths()`. Naturally, my packages started not working. My scripts failed, the error being `Error in library(tidy verse) : there is no package called ‘tidyverse’`. I tried installing the tidyverse and it failed with `object 'pkgInfo' not found` error. Then I managed to re-install most tidyverse packages with the exception of `broom`. I tired re-installing `broom`, `lme4` and I get the same "object 'pkgInfo' not found error". I tried tracking the issue by reading error messages and thought it was a RcppEigen issue but it might not be! That said `Rcpp` package seems to load fine. Any suggestions are appreciated! 

```
> install.packages("lme4")
Installing package into ‘/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
also installing the dependency ‘RcppEigen’

trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/RcppEigen_0.3.3.5.0.tar.gz'
Content type 'application/x-gzip' length 1633859 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

trying URL 'https://cran.ma.imperial.ac.uk/src/contrib/lme4_1.1-19.tar.gz'
Content type 'application/x-gzip' length 4120276 bytes (3.9 MB)
==================================================
downloaded 3.9 MB

* installing *source* package ‘RcppEigen’ ...
** package ‘RcppEigen’ successfully unpacked and MD5 sums checked
** libs
icpc  -I"/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/include" -DNDEBUG  -I"/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -xHost  -c RcppEigen.cpp -o RcppEigen.o
icpc  -I"/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/include" -DNDEBUG  -I"/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -xHost  -c RcppExports.cpp -o RcppExports.o
icpc  -I"/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/include" -DNDEBUG  -I"/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include  -I../inst/include -fpic  -xHost  -c fastLm.cpp -o fastLm.o
icc -std=gnu99 -I"/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/include" -DNDEBUG  -I"/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -I/usr/local/include   -fpic  -xHost  -c init.c -o init.o
icpc -shared -L/usr/local/lib64 -o RcppEigen.so RcppEigen.o RcppExports.o fastLm.o init.o -L/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/lib -lRlapack -L/apps/languages/R/3.5.1/el7/AVX512/intel-2018/lib64/R/lib -lRblas -lifport -lifcoremt -limf -lsvml -lm -lipgo -lirc -lpthread -lirc_s -ldl
installing to /nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen/libs
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(j <- imp[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
  object 'pkgInfo' not found
ERROR: lazy loading failed for package ‘RcppEigen’
* removing ‘/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen’
ERROR: dependency ‘RcppEigen’ is not available for package ‘lme4’
* removing ‘/nfshome/store03/users/c.c1541911/R/x86_64-pc-linux-gnu-library/3.5/lme4’

The downloaded source packages are in
	‘/tmp/RtmppNWEih/downloaded_packages’
Warning messages:
1: In install.packages("lme4") :
  installation of package ‘RcppEigen’ had non-zero exit status
2: In install.packages("lme4") :
  installation of package ‘lme4’ had non-zero exit status
```

**Comment by eddelbuettel** [comment]
That' still nested: lme4 calling RcppEigen. Figure out RcppEigen on its own.  If it doesn't work look at _its_ dependencies, maybe you need to repair Rcpp first?

(Gentle handwave. My wife has relatives in Wales and I visited the Rhonda valley years back. Am also a former slurm user and used to look after slurm too for Debian for a bit.  Nice tool.   But yes, large installations are fragile and you may be hosed now til admins come back / help with backups etc pp.  At least you know it once worked so there is hope of getting it back eventually...)

**Comment by eddelbuettel** [comment]
The `loadNamespace` failure is puzzling. It shouldn't try to look at other paths.

Just for our sanity:  define a new first for entry for `.libPaths`, say `~/tmpRlib`.  Try installing Rcpp there. Then try installing RcppEigen.  

(Sorry about the rookie spelling error with Rhondda.  I should have known better. ;-)

**Comment by eddelbuettel** [comment]
Please:

> Selection: 60

I think I am not getting through to you.  If you still think that installing 60 packages is the way to go about debugging the installation of a single one then I am wasting my time.

I also recommend hard-wiring a mirror in your system-wide (maybe you can't) or personal `.Rprofile`:

```sh
edd@rob:~$ grep -C2 cloud /etc/R/Rprofile.site
#})

## We set the cloud mirror, which is 'network-close' to everybody, as default
local({
    r <- getOption("repos")
    r["CRAN"] <- "https://cloud.r-project.org"
    options(repos = r)
})
edd@rob:~$ 
```

**Comment by eddelbuettel** [comment]
As for the RcppEigen error: beats me.  Truly sorry but I don't think I can offer any more help here. It not something I have seen in 20+ years with R.

**Comment by sefabey** [comment]
> ## We set the cloud mirror, which is 'network-close' to everybody, as default local({ r <- getOption("repos") r["CRAN"] <- "https://cloud.r-project.org" options(repos = r) })

I'm sorry, could not help but notice the edited bit as it popped up in my email notifications. Have I done sth wrong? If so, my apologies. Never meant to waste your time. 

Thanks for the .Rprofile suggestion, I'll try to do it. 

As for RcppEigen, as a last resort, I tried a fresh .libPaths(), installing Rcpp only (w/o dependencies) and then RcppEigen (again, w/o dependencies) and still getting the same error. I'll send an email to my sysadmin and hope they can fix the issue. Regardless of the outcome, appreciate the help and thank you for your time.

**Comment by sefabey** [comment]
Thanks anyway. I passed the issue on to my sysadmin.

**Comment by sefabey** [comment]
Hello again, 

Just for the closure, I've managed to sort this issue out. I've deleted my `.libPaths()` completely and got R to prompt me to create a new one and after that, I managed to install RcppEigen (hence reverse dependencies) w/o problems. Although this still does not make sense as I had tried effectively the same by changing the `.libPaths()` previously but I'm so glad to get my packages to work, I do not mind to debug further. 

Also your suggestion to add a CRAN mirror to `.Rprofile` worked perfectly (was hesitant bc of permisions). Lastly, was influenced by your first comment and I've been using `ag` since. I'm amazed how useful and fast it works. Thank you!

**Comment by eddelbuettel** [comment]
Thanks for reporting back, and sorry for the woes.  C++ _does_ sometimes require rebuilds, and that is what you ran into.  The fact that our depedency graphs get bigger does not help.  But by drilling down one often manages to get to the cause.  Glad you have it working.
