### ISSUE TITLE
mkl.h missing in installation on cluster with R 3.5.2

### ISSUE THREAD

**Issue by mebrooks** [RcppCore/RcppEigen#67]
I just updated to R 3.5.2 on my campus's computing cluster and I'm trying to install RcppEigen.  According to a Google search of the error (`mkl.h No such file or directory`), I need to add something like 
```
source /opt/intel/bin/compilervars.sh intel64
```
to the .bashrc file. However, this extension doesn't work on my system. Do you know how to make it find mkl.h?  I've contacted the cluster system admins about this, but I thought maybe someone here would know what to do.

```
trying URL 'https://stat.ethz.ch/CRAN/src/contrib/RcppEigen_0.3.3.5.0.tar.gz'
Content type 'application/x-gzip' length 1633859 bytes (1.6 MB)
==================================================
downloaded 1.6 MB

* installing *source* package 'RcppEigen' ...
** package 'RcppEigen' successfully unpacked and MD5 sums checked
** libs
g++  -I"/appl/R/3.5.2-sl64/lib64/R/include" -DNDEBUG  -I"/zhome/61/6/119429/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" -DEIGEN_USE_MKL_ALL -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I/usr/local/include  -I../inst/include -fpic  -I/appl/R/3.5.2-sl64/include -O2 -fomit-frame-pointer  -c RcppEigen.cpp -o RcppEigen.o
In file included from ../inst/include/Eigen/Core:100:0,
                 from ../inst/include/Eigen/Dense:1,
                 from ../inst/include/RcppEigenForward.h:30,
                 from ../inst/include/RcppEigen.h:25,
                 from RcppEigen.cpp:22:
../inst/include/Eigen/src/Core/util/MKL_support.h:58:21: fatal error: mkl.h: No such file or directory
 #   include <mkl.h>
                     ^
compilation terminated.
make: *** [RcppEigen.o] Error 1
ERROR: compilation failed for package 'RcppEigen'
* removing '/zhome/61/6/119429/R/x86_64-pc-linux-gnu-library/3.5/RcppEigen'

The downloaded source packages are in
	'/tmp/RtmptAqN95/downloaded_packages'
Warning message:
In install.packages("RcppEigen") :
  installation of package 'RcppEigen' had non-zero exit status
```

**Comment by eddelbuettel** [comment]
Slowly.  Your installation command echos `DEIGEN_USE_MKL_ALL` which we do not set. Breaking the line up we see

```
g++  -I"/appl/R/3.5.2-sl64/lib64/R/include" -DNDEBUG  \
  -I"/zhome/61/6/119429/R/x86_64-pc-linux-gnu-library/3.5/Rcpp/include" \
  -DEIGEN_USE_MKL_ALL -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION \
  -I/usr/local/include  -I../inst/include -fpic  -I/appl/R/3.5.2-sl64/include -O2 -fomit-frame-pointer  \
  -c RcppEigen.cpp -o RcppEigen.o
```

If you need MKL I guess you (or your campus/cluster) needs to provide it. That has nothing to do with RcppEigen.

For comparison, on my box (with some local Debian/Ubuntu choices as well as `ccache` which I adore):

```
  ccache g++ -I"/usr/share/R/include" -DNDEBUG  -I"/usr/local/lib/R/site-library/Rcpp/include"   \
  -I../inst/include -fpic  -g -O3 -Wall -pipe -DBOOST_NO_AUTO_PTR -Wno-sign-compare \
  -Wno-parentheses -Wno-maybe-uninitialized  -march=native -c RcppEigen.cpp -o RcppEigen.o
```
No RcppEigen as I can tell so I plan to close this. Ok?

**Comment by mebrooks** [comment]
For future users' benefit, I might come back and update with more helpful information on getting MKL once I find it, but it's OK to close this.

**Comment by mebrooks** [comment]
The problem was that the cluster was setup to use openBLAS, but another program I had run before was telling it to use MKL.

The solution was to edit the file `~/.R/Makevars` to remove the part that was telling it to use MKL `CPPFLAGS=-DEIGEN_USE_MKL_ALL -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION -I/usr/local/include`.

I still get several warnings, but at least is seems to work.

**Comment by eddelbuettel** [comment]
Yes, the warnings are an annoyannce.  May make sense to collect a few compiler flags to make it better.

Anyway -- glad you have it working now as this really was a local issue.
