### ISSUE TITLE
Use R's RNG in default example included in skeleton package?

### ISSUE THREAD

**Issue by rstub** [RcppCore/RcppEigen#69]
https://github.com/RcppCore/RcppEigen/blob/9abb4019e732193a245f42f0383e605bd7f85112/inst/include/Eigen/src/Core/MathFunctions.h#L560

Shouldn't R's RNG be used here?

(Reference: https://stat.ethz.ch/pipermail/r-package-devel/2019q1/003687.html)

**Comment by eddelbuettel** [comment]
I am a little disappointed by this Rallf.  You surely know that a _non-included_ header is of no impact in a shared library, no?

**Comment by rstub** [comment]
Maybe I am more dense than normal, but I do not understand why you are refering to a "non-included header" file. The above quoted file is included if one includes `RcppEigen.h`. As it turns out, the default skeleton package using RcppEigen triggers the NOTE from R CMD check that `rand()` should not be used:

```
$  R -e "RcppEigen::RcppEigen.package.skeleton('EigenRand')"
[...]
$ R CMD build EigenRand
[...]
$ R CMD check EigenRand_1.0.tar.gz
[...]
* checking compiled code ... NOTE
File ‘EigenRand/libs/EigenRand.so’:
  Found ‘rand’, possibly from ‘rand’ (C)
    Object: ‘rcppeigen_hello_world.o’

Compiled code should not call entry points which might terminate R nor
write to stdout/stderr instead of to the console, nor use Fortran I/O
nor system RNGs.

See ‘Writing portable packages’ in the ‘Writing R Extensions’ manual.
* checking examples ... OK
* checking PDF version of manual ... OK
* DONE

Status: 1 NOTE
See
  ‘/tmp/EigenRand.Rcheck/00check.log’
for details.

$ nm -A -g -C EigenRand.Rcheck/00_pkg_src/EigenRand/src/*o | grep rand
EigenRand.Rcheck/00_pkg_src/EigenRand/src/EigenRand.so:                 U rand@@GLIBC_2.2.5
EigenRand.Rcheck/00_pkg_src/EigenRand/src/rcppeigen_hello_world.o:                 U rand
```

Probably due to this line:

https://github.com/RcppCore/RcppEigen/blob/9abb4019e732193a245f42f0383e605bd7f85112/inst/skeleton/rcppeigen_hello_world.cpp#L20

One might argue that this case is pathologic. I am not sure, though, how the OP of that thread on r-pkg-devel managed to trigger that NOTE.

**Comment by eddelbuettel** [comment]
Hm. Did anything change there?  Lemme reopen then...

**Comment by eddelbuettel** [comment]
Oh, I see now what you mean.  That is a stupid example -- will change to calling R's RNG.

**Comment by eddelbuettel** [comment]
From the top of your head, any other good initializers you'd recomment [from here](https://eigen.tuxfamily.org/dox/group__TutorialAdvancedInitialization.html) ?  Maybe `LinSpaced` ?

**Comment by eddelbuettel** [comment]
Draft:

```c++
Eigen::MatrixXd rcppeigen_hello_world() {
    Eigen::MatrixXd m1 = Eigen::MatrixXd::Identity(3, 3);
    //Eigen::MatrixXd m2 = Eigen::MatrixXd::Random(3, 3);
    Eigen::MatrixXd m2 = Eigen::MatrixXd::Zero(3, 3);
    for (auto i=0; i<m2.rows(); i++)
        for (auto j=0; j<m2.cols(); j++)
            m2(i,j) = R::rnorm(0, 1);

    return m1 + 3 * (m1 + m2);
}
```

**Comment by rstub** [comment]
That removes the NOTE for the default skeleton, but the fundamental problem remains. One can trigger Eigen into using `std::rand()` even in less obvious ways than calling a method called `Random`. For example, the following function also triggers the `rand()` NOTE:

```cpp
Eigen::MatrixXd rcppeigen_hello_world() {
    Eigen::MatrixXd m1 = Eigen::MatrixXd::Identity(3, 3);
    //Eigen::MatrixXd m2 = Eigen::MatrixXd::Random(3, 3);
    Eigen::MatrixXd m2 = Eigen::MatrixXd::Zero(3, 3);
    for (auto i=0; i<m2.rows(); i++)
        for (auto j=0; j<m2.cols(); j++)
            m2(i,j) = R::rnorm(0, 1);

    Eigen::RealQZ<Eigen::MatrixXd> qz(3);
    qz.compute(m1,m2);
    
    return m1 + 3 * (m1 + m2);
}
```

since `Eigen::RealQZ` uses `internal::random()` (which in turn uses `std::rand()`) in some corner cases:

https://github.com/RcppCore/RcppEigen/blob/9abb4019e732193a245f42f0383e605bd7f85112/inst/include/Eigen/src/Eigenvalues/RealQZ.h#L439-L442

**Comment by eddelbuettel** [comment]
I am sorry. I do not understand what you're after here.

I believe we are both aware that _Writing R Extensions_ and the `R CMD check` tests dislike the C library RNG.   Which is why we are rewriting it in ways to NOT trigger it.

As opposed to enumerating all possible ways to trigger it.   So why would `RealQZ()` help?

As I said at the outset, I do not consider myself here in the role of an editor or reviewer for Eigen code.  If they include code that _may_ trigger R warnings I officially do not care. I am here to support the basic use cases not involving `rand`.

**Comment by rstub** [comment]
I meanwhile think that the OP of that r-pkg-devel thread used the `Random` method. In that case it might be sufficient to document some restrictions:

> Don't use `Random()` or `RealQZ` if you want to submit your package to CRAN.

**Comment by eddelbuettel** [comment]
Yes. Writing R Extension does that.  R CMD check checks for it.  But I also do not house visits to patch their system's C library.

**Comment by rstub** [comment]
> As I said at the outset, I do not consider myself here in the role of an editor or reviewer for Eigen code. If they include code that _may_ trigger R warnings I officially do not care. I am here to support the basic use cases not involving `rand`.

Ok, fair enough. In that case the proposed change to `rcppeigen_hello_world()` is sufficient.

**Comment by eddelbuettel** [comment]
Good to have agreement.  Shipping examples that trigger warnings and hence do not provide best practives is something I don't like so thanks for pointing me here.  That had long been overlook.
