### ISSUE TITLE
Enabling OpenMP

### ISSUE THREAD

**Issue by coatless** [RcppCore/RcppEigen#70]
Similar to RcppArmadillo, there is the possibility of a speedup by enabling OpenMP for RcppEigen. Though, I'm not sure about repeating the heartache associated with RcppArmadillo. 

The main changes are:

1. The plugin manager would need the proper `OPENMP` variables:

https://github.com/RcppCore/RcppEigen/blob/master/R/inline.R#L18

2. The package skeleton's `Makevars` file can be updated to include: 

```bash
PKG_CPPFLAGS=$(SHLIB_OPENMP_CXXFLAGS)
PKG_LIBS=$(SHLIB_OPENMP_CXXFLAGS)
```

**Comment by eddelbuettel** [comment]
Possible headaches:

- EIGEN_DONT_PARALLELIZE - if defined, this disables multi-threading. This is only relevant if you enabled OpenMP. See Eigen and multi-threading for details. (Source:  https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html)

referenced from the longer [Eigen and multi-threading](https://eigen.tuxfamily.org/dox/TopicMultiThreading.html)

Looks like headaches.
