### ISSUE TITLE
Installing RcppEigen crashes RStudio

### ISSUE THREAD

**Issue by KamilKraw** [RcppCore/RcppEigen#85]
Hi,

I don't know why but running install.packages("RcppEigen") and install_github(...) crashed my RStudio on Linux..

One thing that worked for me was run the R itself in terminal and then install the package.

**Comment by eddelbuettel** [comment]
This is a little short on pertinent information:

1. What operating system?
1. How are you running it? Directly, cloud, docker?
1. How much RAM?
1. Source or binary?

There is obviously no issue with RcppEigen has it always has, and continues to, install well on all CRAN machines, see https://cloud.r-project.org/web/checks/check_results_RcppEigen.html

**Comment by eddelbuettel** [comment]
Closing this as it is a stale issue. Please let me know if you still have problems with the current release 0.3.3.9.1.

**Comment by TinoMalija** [comment]
Experiencing the same issue @eddelbuettel 

This's been after unlinking "00LOCK-RcppEigen" that interferes with an automatic process of installing the "stm" package, that depends of RcppEigen to run.

Working on windows 10 Pro OS. Running from R Studio cloud. Laptop's got 16GB of RAM.

Not sure about the source/binary question though.

I'll appreciate any leed.

**Comment by eddelbuettel** [comment]
I cannot help you.  CRAN creates those windows binaries and (literally) thousands of people install them daily or weekly.  I strongly suspect this local to your machine.

Also, always the first thing to try is installation outside of RStudio.
