### ISSUE TITLE
fastLm() argument name clash with apply()

### ISSUE THREAD

**Issue by EddieYang211** [RcppCore/RcppEigen#87]
Hi,

I was trying to residualize many columns in a matrix using apply() and RcppEigen::fastLm() but it seems that both functions take an argument "X", causing error.

Here is an example:

```
// residualize columns 3,4 against columns 1,2
a <- matrix(1:8, 2, 4)
apply(a[,3:4], 2, RcppEigen::fastLm, X=a[,1:2])
```

Running the above lines generate the following error:

```
Error in match.fun(FUN) : '2' is not a function, character or symbol
```

Is there a way around this or would it be possible to change the argument names of fastLm()?

Thanks!

**Comment by eddelbuettel** [comment]
Of course there is; define a proper local function, or use _e.g._ `mapply` to apply with multiple args.

Is that really the error you got?  Expecting a _function_ in position two makes me think you ran `sapply` or `lapply`, not `apply`.  I am closing this at it has nothing to with RcppEigen.
