### ISSUE TITLE
SparseSelfAdjointView.h:... warning: .... [-Wtautological-compare]

### ISSUE THREAD

**Issue by f-rousset** [RcppCore/RcppEigen#88]
Hi,
GCC 10.1.0 (Debian 10.1.0-1) emits a "significant" (according to CRAN check results) warning  
`RcppEigen/include/Eigen/src/SparseSelfAdjointView.h:456:14: warning: bitwise comparison always evaluates to false [-Wtautological-compare]`
and same issue at `SparseSelfAdjointView.h:489:14` 

These warnings are reported in `r-devel-linux-x86_64-debian-gcc `  checks for at least two packages [here](https://cran.r-project.org/web/checks/check_results_spaMM.html) and [there](https://cran.r-project.org/web/checks/check_results_DDRTree.html) and I know no other configuration that reports it (meaning in particular that did not reproduce it myself). 

Should I report this upstream ? The current SparseSelfAdjointView.h file is identical to the one included in RcppEigen as far as I can see.

Best,

F.

Edit: from the comments, the warnings are expected to disappear soon from the cran check pages.

**Comment by eddelbuettel** [comment]
> Should I report this upstream ?

Yes please!  Eigen development appears to be slower which is not uncommon for a mature project, but responsive.  We have seen several bug fixes in recent years.  If you hear something back can you let us know here too?

**Comment by kevinushey** [comment]
FWIW it looks like R-devel now omits these checks:

https://github.com/wch/r-source/commit/bd976c155b3868c4daaa3a3aec3bef04e611c861

(although I'm sure they'd be happy to see these warnings gone, nonetheless)

**Comment by eddelbuettel** [comment]
Nice catch there!

**Comment by f-rousset** [comment]
Caught before hiding... and nevertheless now [reported](https://gitlab.com/libeigen/eigen/-/issues/1901) to Eigen.

**Comment by eddelbuettel** [comment]
I am closing this as it should be taken care of in Eigen 3.3.9 which just got to CRAN as RcppEigen 0.3.3.9.1.  Let me know if you still have issues.
