### ISSUE TITLE
Configuration to reduce console output?

### ISSUE THREAD

**Issue by bbimber** [RcppCore/RcppEigen#90]
We are building an R project on travis-ci with many dependencies.  RcppEigen 0.3.3.7.0 is installed.  The console output from anything involving RcppEigen is huge, and we're hitting limits on travis-ci with respect to log size.  I googled this, and tried a few things, including setting "CXXFLAGS=$CXXFLAGS -w  -DEIGEN_PERMANENTLY_DISABLE_STUPID_WARNINGS" in $HOME/.R/Makevars.  These flags are passed to many g++ commands, but many dont seem to inherit this.  Are there any additional config options I can set to reduce the console output from RcppEigen?  Thanks in advance.

One example output is here:

https://api.travis-ci.com/v3/job/379691434/log.txt

the first few lines of an example are: 

begin installing package â€˜RSQLiteâ€™
* installing *source* package â€˜DDRTreeâ€™ ...
** package â€˜DDRTreeâ€™ successfully unpacked and MD5 sums checked
** using staged installation
** libs
make[1]: Entering directory '/tmp/Rtmpuvoour/R.INSTALL2854527da0ed/DDRTree/src'
g++ -std=gnu++11 -I"/opt/R/3.6.3/lib/R/include" -DNDEBUG  -I"/home/travis/R/Library/Rcpp/include" -I"/home/travis/R/Library/RcppEigen/include" -I"/home/travis/R/Library/BH/include" -I/usr/local/include  -fpic  -g -O2  -c DDRTree.cpp -o DDRTree.o
In file included from /home/travis/R/Library/RcppEigen/include/Eigen/Core:392:0,
                 from /home/travis/R/Library/RcppEigen/include/Eigen/Dense:1,
                 from /home/travis/R/Library/RcppEigen/include/RcppEigenForward.h:30,
                 from /home/travis/R/Library/RcppEigen/include/RcppEigen.h:25,
                 from DDRTree.h:5,
                 from DDRTree.cpp:1:
/home/travis/R/Library/RcppEigen/include/Eigen/src/Core/arch/SSE/PacketMath.h:60:39: warning: ignoring attributes on template argument â€˜__m128 {aka __vector(4) float}â€™ [-Wignored-attributes]
 template<> struct is_arithmetic<__m128>  { enum { value = true }; };
                                       ^

**Comment by eddelbuettel** [comment]
Good point. I keep a few options "locally" in `~/.R/Makevars` because we are "not allowed" to set them in the `src/Makevars{,.in}` for reasons of "portability".   CRAN has its methods and reason but sometimes you wonder...

So the quickest hack I can think of is to simple run a few lines of shell code to echo or cat into `~/.R/Makevars` on your Travis account (or prepare and commit a file and just copy it in).

There is little we can do for the official package because of the CRAN Repository Policy.

**Comment by bbimber** [comment]
@eddelbuettel so what are those lines of code?

**Comment by eddelbuettel** [comment]
Not claiming these are perfect for _your_ issue but I would just add compiler flags til Boost and Eigen are quiet. They usually tell you at the end of each line what triggered them so this gives _an_ idea:

```make
#PEDANTIC=-pedantic -Werror -DBOOST_NO_AUTO_PTR
#PEDANTIC=-pedantic -DBOOST_NO_AUTO_PTR -Wno-ignored-attributes
#PEDANTIC=-pedantic -DBOOST_NO_AUTO_PTR
#PEDANTIC= -DBOOST_NO_AUTO_PTR -Wno-sign-compare -Wno-parentheses -Wno-maybe-uninitialized
PEDANTIC=-pedantic
#PEDANTIC=-DBOOST_NO_AUTO_PTR

#XTRAFLAGS=-Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-class-memaccess
#XTRAFLAGS=-Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes -Wno-parentheses -Wno-address-of-packed-member
#XTRAFLAGS=-Wno-misleading-indentation -Wno-unused -Wno-ignored-attributes
#XTRAFLAGS=-Wno-misleading-indentation -Wno-unused -march=native
#XTRAFLAGS=-Wno-misleading-indentation -Wno-ignored-attributes
#XTRAFLAGS=-Wno-deprecated-declarations -Wno-parentheses
#XTRAFLAGS=-Wno-ignored-attributes -Wno-deprecated-declarations -fno-common
#XTRAFLAGS=-Wno-deprecated-declarations -Wno-parentheses
#XTRAFLAGS=-Wno-parentheses
#XTRAFLAGS=-mshstk
#XTRAFLAGS=-Wno-ignored-attributes
XTRAFLAGS=
```
