### ISSUE TITLE
Eigen 3.3.8 release candidate

### ISSUE THREAD

**Issue by SteveBronder** [RcppCore/RcppEigen#91]
Just an fyi there's a release candidate for [Eigen 3.3.8](https://gitlab.com/libeigen/eigen/-/tags/3.3.8-rc1) available

[Change Log](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3.8-rc1)

**Comment by eddelbuettel** [comment]
Would be a nice exercise for a volunteer to package up and to carry our (accumulated and still needed patches) forward. We could put a RC package in a drat for us all to noodle over.   Else it may have to wait til release.

**Comment by SteveBronder** [comment]
I think I could do that this week or next

**Comment by eddelbuettel** [comment]
Great.  This directory may help:  https://github.com/RcppCore/RcppEigen/tree/master/patches

Having a rc package would help with rev.deps. I can turn on the usual machinery if we have something.

**Comment by rok-cesnovar** [comment]
The release was published in October. Is there any timeline on when Eigen 3.3.8 will be available in RcppEigen? Let us know if we (Stan devs) can help with the upgrade. Thanks!

**Comment by eddelbuettel** [comment]
It would be great if one or more you could work on that.  Happy to provide guidance, and (towards the end) run reverse-depends.

It is a bit more involved than just copying files in as the `patches/` directory shows, but not _that much_ and `R CMD check` (especially under `r-devel` should be pretty clear what it dislikes).
