### ISSUE TITLE
SparseCwiseUnaryOp.h      Error: Cannot define member of undefined specialization "unary_evaluator<CwiseUnaryOp<UnaryOp, ArgType>, Eigen::internal::IteratorBased>

### ISSUE THREAD

**Issue by Jiang-Kangkang** [RcppCore/RcppEigen#94]
I just made a R package using RcppEigen. When I doing some checking in r-hub, everything is ok in all platforms except the platform (Oracle Solaris 10, x86, 32 bit, R-release, Oracle Developer Studio 12.6). It gives some errors like "/export/home/XvbHDkA/R/RcppEigen/include/Eigen/src/SparseCore/SparseCwiseUnaryOp.h", line 49: Error: Cannot define member of undefined specialization "unary_evaluator<CwiseUnaryOp<UnaryOp, ArgType>, Eigen::internal::IteratorBased>". I have searched this problem but no result  except some same problems in R package checking. I don't see any hints in my code. Could you help  me with this problem. Picture of the problem is as followed.  Any additional information you require, please tell me.
![R package problem](https://user-images.githubusercontent.com/42855591/104796434-1d957100-57f1-11eb-83d4-1a24ffc3d16c.png)

**Comment by eddelbuettel** [comment]
(Please do not post images.  Try to edit your post and edit the output in, maybe inside a code block.)

Maybe the compiler is different, or older.  We have no influence over the choice of tools at the CRAN side of things.

**Comment by Jiang-Kangkang** [comment]
I got this problem when I was doing the  R CMD check. Detailed error information is as followed.
"""""""""""""""""""""""""""""""
>>>>>============== Running R CMD check
Using R at /opt/R/R-4.0.3/bin/R
* using log directory ‘/export/home/XSn3fFg/BeSS.Rcheck’
* using R version 4.0.3 (2020-10-10)
* using platform: i386-pc-solaris2.10 (32-bit)
* using session charset: UTF-8
* checking for file ‘BeSS/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘BeSS’ version ‘1.0.9’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘BeSS’ can be installed ... 
* ERROR
*  """"""""""""""""""""""""""""""""""""""""""""""""

"""""""""""""""""""""""""""""""""""""""""""""""""""
* installing *source* package BeSS ...
** package BeSS successfully unpacked and MD5 sums checked
** using staged installation
** libs
/opt/developerstudio12.6/bin/CC -std=c++11 -library=stdcpp,CrunG3 -I"/opt/R/R-4.0.3/lib/R/include" -DNDEBUG  -I'/export/home/XSn3fFg/R/Rcpp/include' -I'/export/home/XSn3fFg/R/RcppEigen/include' -I/opt/csw/include   -KPIC  -O -xlibmil -xtarget=native -xcache=generic -nofstore  -c RcppExports.cpp -o RcppExports.o
"/export/home/XSn3fFg/R/RcppEigen/include/Eigen/src/SparseCore/SparseCwiseUnaryOp.h", line 49: Error: Cannot define member of undefined specialization "unary_evaluator<CwiseUnaryOp<UnaryOp, ArgType>, Eigen::internal::IteratorBased>".
"/export/home/XSn3fFg/R/RcppEigen/include/Eigen/src/SparseCore/SparseCwiseUnaryOp.h", line 100: Error: Cannot define member of undefined specialization "unary_evaluator<CwiseUnaryView<ViewOp, ArgType>, Eigen::internal::IteratorBased>".
"/export/home/XSn3fFg/R/RcppEigen/include/Eigen/src/SparseCore/SparseBlock.h", line 503: Error: Cannot define member of undefined specialization "unary_evaluator<Block<ArgType, BlockRows, BlockCols, InnerPanel>, Eigen::internal::IteratorBased>".
"/export/home/XSn3fFg/R/RcppEigen/include/Eigen/src/SparseCore/SparseBlock.h", line 529: Error: Cannot define member of undefined specialization "unary_evaluator<Block<ArgType, BlockRows, BlockCols, InnerPanel>, Eigen::internal::IteratorBased>".
4 Error(s) detected.
gmake: *** [/opt/R/R-4.0.3/lib/R/etc/Makeconf:181: RcppExports.o] Error 2
""""""""""""""""""""""""""""""""""""""""""""""""
[Here](https://artifacts.r-hub.io/BeSS_1.0.9.tar.gz-151a21758dd8ac4a3fdb49144c7e05c6) is the page of this problem. Do you  have some idea how to solve the problem?

**Comment by Jiang-Kangkang** [comment]
> (Please do not post images. Try to edit your post and edit the output in, maybe inside a code block.)
> 
> Maybe the compiler is different, or older. We have no influence over the choice of tools at the CRAN side of things.

I got this problem when I was doing the R CMD check. Detailed error information is as followed.
`
>>>>>============== Running R CMD check
Using R at /opt/R/R-4.0.3/bin/R
* using log directory ‘/export/home/XSn3fFg/BeSS.Rcheck’
* using R version 4.0.3 (2020-10-10)
* using platform: i386-pc-solaris2.10 (32-bit)
* using session charset: UTF-8
* checking for file ‘BeSS/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘BeSS’ version ‘1.0.9’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘BeSS’ can be installed ... ERROR
`

`
* installing *source* package BeSS ...
** package BeSS successfully unpacked and MD5 sums checked
** using staged installation
** libs
/opt/developerstudio12.6/bin/CC -std=c++11 -library=stdcpp,CrunG3 -I"/opt/R/R-4.0.3/lib/R/include" -DNDEBUG  -I'/export/home/XSn3fFg/R/Rcpp/include' -I'/export/home/XSn3fFg/R/RcppEigen/include' -I/opt/csw/include   -KPIC  -O -xlibmil -xtarget=native -xcache=generic -nofstore  -c RcppExports.cpp -o RcppExports.o
"/export/home/XSn3fFg/R/RcppEigen/include/Eigen/src/SparseCore/SparseCwiseUnaryOp.h", line 49: Error: Cannot define member of undefined specialization "unary_evaluator<CwiseUnaryOp<UnaryOp, ArgType>, Eigen::internal::IteratorBased>".
"/export/home/XSn3fFg/R/RcppEigen/include/Eigen/src/SparseCore/SparseCwiseUnaryOp.h", line 100: Error: Cannot define member of undefined specialization "unary_evaluator<CwiseUnaryView<ViewOp, ArgType>, Eigen::internal::IteratorBased>".
"/export/home/XSn3fFg/R/RcppEigen/include/Eigen/src/SparseCore/SparseBlock.h", line 503: Error: Cannot define member of undefined specialization "unary_evaluator<Block<ArgType, BlockRows, BlockCols, InnerPanel>, Eigen::internal::IteratorBased>".
"/export/home/XSn3fFg/R/RcppEigen/include/Eigen/src/SparseCore/SparseBlock.h", line 529: Error: Cannot define member of undefined specialization "unary_evaluator<Block<ArgType, BlockRows, BlockCols, InnerPanel>, Eigen::internal::IteratorBased>".
4 Error(s) detected.
gmake: *** [/opt/R/R-4.0.3/lib/R/etc/Makeconf:181: RcppExports.o] Error 2
`

The Platform is  Oracle Solaris 10, x86, 32 bit, R-release, Oracle Developer Studio 12.6.

[Here](https://artifacts.r-hub.io/BeSS_1.0.9.tar.gz-151a21758dd8ac4a3fdb49144c7e05c6) is the error page Rhub return. Do you have some idea how to solve it?

**Comment by Jiang-Kangkang** [comment]
I was surprised to find that there was no problem when I uploaded my package to R CRAN, maybe it was a problem of their platform. Thank you anyway.
