### ISSUE TITLE
Backporting RcppEigen patches to Eigen

### ISSUE THREAD

**Issue by SteveBronder** [RcppCore/RcppEigen#97]
I made an issue about backporting some of the RcppEigen patches to Eigen which should hopefully make future releases easy peasy. @eddelbuettel would you mind looking/commenting on the response to the Eigen issue below? idt I have enough context to understand some of the patches for warnings beyond "CRAN is unhappy about these"

https://gitlab.com/libeigen/eigen/-/issues/2196

**Comment by eddelbuettel** [comment]
Sorry, I am likely with them here.

CHOLMOD is something @dmbates  introduced  way-back-when.  He will be in a better position to comment on its general usefulness to Eigen, or lack thereof.  I have this filed under something somewhat specific to R.

The error suppressant is quite frankly [redacted by legal team].  But that is the tax we pay for being on CRAN: Sometimes we may well think that what they do is wrong, but we do not have a leg to stand on to change it.  As I often say, "life's a b%^tch and then you die".

**Comment by SteveBronder** [comment]
lol yeah I get the error suppression is a CRAN thing but wanted to double check if there was any extra context. I'll talk with their team more to sort out which things do or don't make sense to backwards patch

**Comment by eddelbuettel** [comment]
100% agree with the sentiment of moving anything of value upstream.  Thanks for looking into it.
